# Pull in python for access to pip for hererocks
language: python

sudo: false

branches:
    only:
        - master
        - next
        - 1.2.x
        - 1.1.x
        - 1.0.x

env:
    global:
        - LUAROCKS=2.4.2
    matrix:
        - LPEG=1.0.1-1 LUA="luajit 2.1"
        - LPEG=1.0.1-1 LUA="luajit 2.0"
        - LPEG=1.0.1-1 LUA="lua 5.3"
        - LPEG=1.0.1-1 LUA="lua 5.2"
        - LPEG=1.0.1-1 LUA="lua 5.1"
        - LPEG=0.12.2-1 LUA="luajit 2.1"
        - LPEG=0.12.2-1 LUA="luajit 2.0"
        - LPEG=0.12.2-1 LUA="lua 5.3"
        - LPEG=0.12.2-1 LUA="lua 5.2"
        - LPEG=0.12.2-1 LUA="lua 5.1"
        - LPEG=0.10.2-1 LUA="luajit 2.0"
        - LPEG=0.10.2-1 LUA="lua 5.2"
        - LPEG=0.10.2-1 LUA="lua 5.1"
        - LPEG=0.9-1 LUA="luajit 2.0"
        - LPEG=0.9-1 LUA="lua 5.1"
        - LPEG=0.8.1-1 LUA="luajit 2.0"
        - LPEG=0.8.1-1 LUA="lua 5.1"
        - LPEG=0.7-3 LUA="luajit 2.0"
        - LPEG=0.7-3 LUA="lua 5.1"

branches:
    only:
        - master
        - /^feature[/]/

before_install:
    - pip install hererocks
    - hererocks here -r $LUAROCKS --$LUA
    - export PATH=$(pwd)/here/bin:$PATH
    - luarocks install luacov
    - luarocks install lunitx
    - luarocks install luafilesystem
    - luarocks install lpeg $LPEG

script:
    - make LUA_BIN=lua LUNIT_BIN=lunit.sh LUA_INIT="require('luarocks.loader');require('luacov')" check

after_success:
    # Rework the stats file and generate
    - sed -e "s|../lua/|lua/|" < tests/luacov.stats.out > luacov.stats.out
    - luacov
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        on_success: change
        on_failure: always
